#!/usr/bin/env bash
#
# install-commit-msg.sh — install a Git commit-msg hook that enforces the
# Nightshift Conventional Commits convention.
#
# Usage:  scripts/install-commit-msg.sh [repo-root]
#
# The hook runs `go run ./cmd/commit-lint` on the staged commit message and
# rejects the commit when the message does not conform. Re-run this script after
# cloning to re-enable enforcement.
set -euo pipefail

repo_root="${1:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
hooks_dir="$repo_root/.git/hooks"
hook_path="$hooks_dir/commit-msg"

mkdir -p "$hooks_dir"

cat >"$hook_path" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-commit-msg.sh — enforces Conventional Commits.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
export GOFLAGS=-mod=mod

if ! go run "$REPO_ROOT/cmd/commit-lint" "$1"; then
	exit 1
fi
HOOK

chmod +x "$hook_path"

echo "Installed commit-msg hook at: $hook_path"
echo "Future commits will be validated against the Conventional Commits convention."
